# SPDX-FileCopyrightText: 2021 fosslinux <fosslinux@aussies.space>
# SPDX-FileCopyrightText: 2021 Andrius Štikonas <andrius@stikonas.eu>
#
# SPDX-License-Identifier: GPL-3.0-or-later

pylint_task:
  container:
    image: debian:bullseye
  deps_script:
    - apt-get -y update
    - apt-get -y dist-upgrade
    - apt-get -y install python3-requests pylint
    - apt-get -y clean
  check_script:
    - pylint rootfs.py sysa.py lib/utils.py

shell_lint_task:
  container:
    image: debian:stable
  deps_script:
    - apt-get -y update
    - apt-get -y dist-upgrade
    - apt-get -y install shellcheck
    - apt-get -y clean
  check_script:
    - shellcheck sysa/run.sh sysa/helpers.sh

reuse_lint_task:
  container:
    image: debian:stable
  deps_script:
    - apt-get -y update
    - apt-get -y dist-upgrade
    - apt-get -y install python3-pip git
    - apt-get -y clean
    - pip3 install reuse
  check_script:
    - reuse lint

run_task:
  timeout_in: 120m
  container:
    image: debian:stable
    use_in_memory_disk: true
  deps_script:
    - apt-get -y update
    - apt-get -y dist-upgrade
    - apt-get -y install sudo git cpio linux-image-4.19.0-16-amd64 expect wget python3-distutils python3-requests
    - apt-get -y clean
  submodule_script:
    - git submodule update --init --recursive
  kernel_script:
    - cp /boot/vmlinuz-4.19.0-16-amd64 ./kernel
  run_script:
    - ./.cirrus.expect | tee -a /tmp/run.log
    - grep -q 'Bootstrapping completed.' /tmp/run.log
