#!/bin/sh
# SPDX-FileCopyrightText: 2024 fosslinux <fosslinux@aussies.space>
#
# SPDX-License-Identifier: GPL-3.0-or-later

../gnulib-5d2fe24/gnulib-tool --import --local-dir=gl \
 --lib=libdiffutils \
 --source-base=lib \
 --m4-base=m4 \
 --doc-base=doc \
 --tests-base=gnulib-tests \
 --aux-dir=build-aux \
 --with-tests \
 --makefile-name=gnulib.mk \
 --no-conditional-dependencies \
 --no-libtool \
 --macro-prefix=gl \
 --avoid=localename \
 --avoid=lock-tests \
 --avoid=setlocale \
 announce-gen \
 argmatch \
 attribute \
 binary-io \
 c-stack \
 config-h \
 diffseq \
 dirname \
 do-release-commit-and-tag \
 dup2 \
 error \
 exclude \
 exitfail \
 extensions \
 extern-inline \
 fcntl \
 file-type \
 filenamecat \
 flexmember \
 fnmatch-gnu \
 getopt-gnu \
 gettext-h \
 gettime \
 git-version-gen \
 gitlog-to-changelog \
 gnu-make \
 gnu-web-doc-update \
 gnumakefile \
 gnupload \
 hard-locale \
 inttostr \
 inttypes \
 isblank \
 largefile \
 lstat \
 maintainer-makefile \
 manywarnings \
 mbrtowc \
 mempcpy \
 mkstemp \
 mktime \
 nstrftime \
 nullptr \
 perl \
 progname \
 propername \
 raise \
 rawmemchr \
 readme-release \
 regex \
 sh-quote \
 signal \
 sigprocmask \
 stat \
 stat-macros \
 stat-time \
 stdbool \
 stdint \
 stpcpy \
 strcase \
 strptime \
 strtoimax \
 sys_wait \
 system-quote \
 time_rz \
 unistd \
 unlocked-io \
 update-copyright \
 verify \
 version-etc \
 version-etc-fsf \
 wcwidth \
 xalloc \
 xfreopen \
 xmalloca \
 xreadlink \
 xstdopen \
 xstrtoimax \
 year2038
