#!/bin/sh

# SPDX-FileCopyrightText: 2023 fosslinux <fosslinux@aussies.space>
#
# SPDX-License-Identifier: GPL-3.0-or-later

../gnulib-356a414e/gnulib-tool --import --local-dir=gnulib-local \
    --lib=libgnu \
    --source-base=lib \
    --m4-base=m4 \
    --doc-base=doc \
    --tests-base=tests \
    --aux-dir=build-aux \
    --lgpl=3 \
    --conditional-dependencies \
    --libtool \
    --macro-prefix=gl \
    --no-vc-files \
    --avoid=lock \
    --avoid=unistr/base \
    --avoid=unistr/u8-mbtouc \
    --avoid=unistr/u8-mbtouc-unsafe \
    --avoid=unistr/u8-mbtoucr \
    --avoid=unistr/u8-prev \
    --avoid=unistr/u8-uctomb \
    --avoid=unitypes \
    accept4 \
    alignof \
    alloca-opt \
    announce-gen \
    autobuild \
    bind \
    byteswap \
    c-strcase \
    canonicalize-lgpl \
    ceil \
    clock-time \
    close \
    connect \
    copysign \
    dirfd \
    dirname-lgpl \
    duplocale \
    environ \
    extensions \
    flexmember \
    flock \
    floor \
    fpieee \
    frexp \
    fstat \
    fsync \
    full-read \
    full-write \
    func \
    gendocs \
    getaddrinfo \
    gethostname \
    getlogin \
    getpeername \
    getsockname \
    getsockopt \
    git-version-gen \
    gitlog-to-changelog \
    gnu-web-doc-update \
    gnupload \
    havelib \
    iconv_open-utf \
    inet_ntop \
    inet_pton \
    isfinite \
    isinf \
    isnan \
    ldexp \
    lib-symbol-versions \
    lib-symbol-visibility \
    libunistring \
    link \
    listen \
    localcharset \
    locale \
    log1p \
    lstat \
    maintainer-makefile \
    malloc-gnu \
    malloca \
    mkdir \
    mkostemp \
    nl_langinfo \
    nproc \
    nstrftime \
    open \
    pipe-posix \
    pipe2 \
    poll \
    posix_spawn \
    posix_spawn_file_actions_addclose \
    posix_spawn_file_actions_adddup2 \
    posix_spawn_file_actions_addopen \
    posix_spawn_file_actions_init \
    posix_spawnp \
    putenv \
    readlink \
    recv \
    recvfrom \
    regex \
    rename \
    rmdir \
    select \
    send \
    sendto \
    setenv \
    setsockopt \
    shutdown \
    socket \
    stat-time \
    stdlib \
    striconveh \
    string \
    sys_select \
    sys_stat \
    time \
    times \
    trunc \
    unistd \
    verify \
    vsnprintf \
    warnings \
    wchar
