#!/usr/bin/bash

# SPDX-FileCopyrightText: 2021 fosslinux <fosslinux@aussies.space>
#
# SPDX-License-Identifier: GPL-3.0-or-later

set -e

# Prepare sysc directory structure
mkdir -p /usr/src
mv run*.sh /usr/src
mv /*-* /usr/src # build scripts

# Begin sysc bootstrapping process
cd /usr/src
exec ./run.sh
