#!/usr/bin/bash

# SPDX-FileCopyrightText: 2021-22 fosslinux <fosslinux@aussies.space>
# SPDX-FileCopyrightText: 2022 Andrius Štikonas <andrius@stikonas.eu>
#
# SPDX-License-Identifier: GPL-3.0-or-later

set -e

PREFIX=/usr
SOURCES="${PREFIX}/src"

export PATH="${PREFIX}/bin"

# shellcheck source=sysa/helpers.sh
. /usr/src/helpers.sh

echo
echo "Installing packages into sysb"

install_tar() {
    echo "${1}: installing package"
    src_apply "$@"
}

# Install needed packages.
install_tar coreutils-5.0 0
install_tar sed-4.0.9 0

install_tar bzip2-1.0.8 0
install_tar coreutils-6.10 0
install_tar e2fsprogs-1.45.7 0
install_tar grep-2.4 0
install_tar kexec-tools-2.0.22 0
install_tar util-linux-2.19.1 0

# Begin sysb bootstrapping process
cd "${SOURCES}"

# shellcheck disable=SC2129
echo "PREFIX=${PREFIX}" >> .env
echo "SOURCES=${SOURCES}" >> .env

exec ./run.sh
