#!/bin/sh
# SPDX-FileCopyrightText: 2024 fosslinux <fosslinux@aussies.space>
#
# SPDX-License-Identifier: GPL-3.0-or-later

../gnulib-3639c57/gnulib-tool --import --local-dir=gl \
 --lib=libm4 \
 --source-base=lib \
 --m4-base=m4 \
 --doc-base=doc \
 --tests-base=tests \
 --aux-dir=build-aux \
 --with-tests \
 --with-c++-tests \
 --makefile-name=gnulib.mk \
 --no-conditional-dependencies \
 --no-libtool \
 --macro-prefix=M4 \
 --avoid=getopt-posix-tests \
 --avoid=lock-tests \
 --avoid=tls-tests \
 announce-gen \
 assert \
 attribute \
 autobuild \
 avltree-oset \
 binary-io \
 c-ctype \
 c-stack \
 clean-temp \
 close-stream \
 closein \
 config-h \
 configmake \
 dirname \
 do-release-commit-and-tag \
 error \
 execute \
 fclose \
 fdl-1.3 \
 fflush \
 filenamecat \
 fopen-gnu \
 fopen-safer \
 fseeko \
 gendocs \
 getopt-gnu \
 gettext-h \
 git-version-gen \
 gitlog-to-changelog \
 gnu-web-doc-update \
 gnumakefile \
 gnupload \
 gpl-3.0 \
 ignore-value \
 intprops \
 maintainer-makefile \
 manywarnings \
 memchr2 \
 mkstemp \
 obstack \
 progname \
 propername \
 regex \
 rename \
 setlocale \
 sigaction \
 sigpipe \
 spawn-pipe \
 stdbool \
 stdint \
 stdlib-safer \
 strsignal \
 strstr \
 strtod \
 unlocked-io \
 update-copyright \
 vc-list-files \
 verify \
 verror \
 version-etc \
 version-etc-fsf \
 wait-process \
 xalloc \
 xoset \
 xprintf \
 xvasprintf-posix
