#!/bin/sh

# SPDX-FileCopyrightText: 2022 Andrius Štikonas <andrius@stikonas.eu>
#
# SPDX-License-Identifier: GPL-3.0-or-later

../gnulib-8f4538a5/gnulib-tool --import --local-dir=gl \
  --lib=libgreputils \
  --source-base=lib \
  --m4-base=m4 \
  --doc-base=doc \
  --tests-base=gnulib-tests \
  --aux-dir=build-aux \
  --with-tests \
  --makefile-name=gnulib.mk \
  --no-conditional-dependencies \
  --no-libtool \
  --macro-prefix=gl \
  --avoid=lock-tests \
  --avoid=mbrtowc-tests \
  --avoid=update-copyright-tests \
  alloca \
  announce-gen \
  argmatch \
  c-ctype \
  c-stack \
  c-strcase \
  closeout \
  configmake \
  dfa \
  dirname-lgpl \
  do-release-commit-and-tag \
  error \
  exclude \
  fcntl-h \
  fdl \
  fnmatch \
  fstatat \
  fts \
  getopt-gnu \
  getpagesize \
  getprogname \
  gettext-h \
  git-version-gen \
  gitlog-to-changelog \
  gnu-web-doc-update \
  gnupload \
  hash \
  ignore-value \
  intprops \
  inttypes \
  isatty \
  isblank \
  iswctype \
  largefile \
  locale \
  lseek \
  maintainer-makefile \
  malloc-gnu \
  manywarnings \
  mbrlen \
  mbrtowc \
  memchr \
  memchr2 \
  mempcpy \
  minmax \
  obstack \
  openat-safer \
  perl \
  propername \
  rawmemchr \
  readme-release \
  realloc-gnu \
  regex \
  safe-read \
  same-inode \
  ssize_t \
  stddef \
  stdlib \
  stpcpy \
  strerror \
  string \
  strstr \
  strtoull \
  strtoumax \
  sys_stat \
  unistd \
  unlocked-io \
  update-copyright \
  useless-if-before-free \
  verify \
  version-etc-fsf \
  wchar \
  wcrtomb \
  wctob \
  wctype-h \
  windows-stat-inodes \
  xalloc \
  xbinary-io \
  xstrtoimax
